###
# static config for traefik
###

log:
  level: DEBUG

api:
  dashboard: true
  insecure: true

providers:
  docker:
    exposedByDefault: false
    network: forbidden
  file:
    filename: /etc/traefik/dynamic.yml

entryPoints:
  web:
    address: ":80"
  redis:
    address: ":6379"      # redis
  postgres:
    address: ":5432"      # postgres
  minio:
    address: ":4572"      # minio
